### ISSUE TITLE
Not sending messages

### ISSUE THREAD

**Issue by johncarterofmars** [jooola/zabbix-matrix-webhook#27]
I am using Zabbix 5.4 and I imported the webhook media type. It is configured according to the instructions. If I test it by removing {ALERT.SENDTO} and replacing it with the room address, I receive a message to the correct room in Element. 

However, alerts are not sent with the user setup to use the Matrix Media Type. 

![user](https://user-images.githubusercontent.com/17039716/198847283-543a2c3e-1848-43d8-bebd-093aaf4e093d.jpg)
![media](https://user-images.githubusercontent.com/17039716/198847287-bfe44c2f-c9d6-4982-b8a3-cf291f7b416d.jpg)

Any suggestions? I appreciate your aid in this.

**Comment by johncarterofmars** [comment]
What I am seeing is that Zabbix thinks there is no Media Type selected for the user. I deleted it from the user, re-added it, and made sure it was enabled.
![dd](https://user-images.githubusercontent.com/17039716/200144261-db92d31b-f048-462f-8620-b868c3a0d655.jpg)
For some reason, Zabbix doesn't know that it's there to call it. 

Again, test messages work and are received. The media type is enabled and the user has it enabled to send messages. 
Any suggestions?

![ksnip_20221105-184711](https://user-images.githubusercontent.com/17039716/200144177-09bd625c-89ca-4afc-bb87-dbd6778ae42e.png)

**Comment by jooola** [comment]
Note that I do not support Zabbix 5.4 as it isn't supported upstream anymore. You should probably upgrade your setup to 6.0 if you want to stick to LTS or 6.2 otherwise.

That said, you could use the 5.0 web hook, and if something is broken fix it, but for that you need the error messages from the action logs.

**Comment by johncarterofmars** [comment]
Thank you for responding. The action logs say: no media defined for user. Telegram works for this user but I have disabled now. 
We are planning to move to 6.2 but we have a lot of template work that would need to be redone so we are forced to take our time with it. 
I have tried both the 5.0 and 6.0 version of the script. 
It is strange that the media type is configured, it shows as enabled, and user has it enabled. But for some reason, Zabbix just doesn't see it.

**Comment by jooola** [comment]
> The action logs say: no media defined for user.

This seem like a configuration problem on your side so I'm gonna close, feel free to reopen with logs and error messages if you think this still has something to do with the matrix webhook.

Another tip, maybe you need to check that your trigger actions (`<zabbix_url>/actionconf.php`) sends events  to all available media types.

**Comment by jooola** [comment]
Hey, I remembered your error, I had it once.

The imported media type failed to import the templates, so it is throwing that you are missing a template for your event.

Check that the media type has some templates configured, if not, you should try to rename the templates field the `media_matrix.json` file.
