### ISSUE TITLE
Support Emojis in messages

### ISSUE THREAD

**Issue by markusn1** [jooola/zabbix-matrix-webhook#28]
I was able to set up this webhook with my own matrix server just fine, thanks!
Previously, I was using telegram with a modified media type (see https://hoctapit.com/zabbix-5-0-telegram-emoji-by-severity-support/).
By using emojis one can see immediately if it is a new problem, or a resolved one.

Would it be able to add emojis in a similar way to your webhook?

Thanks!

**Comment by jooola** [comment]
Thanks a good idea! I'll have a look if this is doable.

I had some issue with Emojis and Element, but that's unrelated to this web hook.

**Comment by jooola** [comment]
I think e40dfc0cd86af5508fc09e2a672515203ca9c3a5 fixes this.
