### ISSUE TITLE
Error: SyntaxError: invalid json (at offset 1)

### ISSUE THREAD

**Issue by NobodyO815** [jooola/zabbix-matrix-webhook#34]
Hi, 

i've got the following error:
00:00:00.000 [Debug] [Matrix Webhook] new request to: https://app.element.io/_matrix/client/r0/rooms/!CbEjPsdXIfbsdBytYK:matrix.org/send/m.room.message
00:00:00.159 [Debug] [Matrix Webhook] Error: SyntaxError: invalid json (at offset 1)

What am i doing wrong? I've set Token, URL and Room ID...
Tanks!

**Comment by jooola** [comment]
See #5
