### ISSUE TITLE
Request failed: 403 Unknown room

### ISSUE THREAD

**Issue by Killerhaschen** [jooola/zabbix-matrix-webhook#8]
Hi i imported the settings and then added a room ID of type "!xxxxxxxx:server.domain.tld", and then the Serve "https://server.domain.tld" and the token. But if i test it i will always get the error:
```
Media type test failed.
Sending failed: Request failed: 403 Unknown room
```
What am id doing wrong?

**Comment by jooola** [comment]
On the top of my head I would say your Room ID is not right. You probably added the matrix server URL to the Room ID, which is probably the cause of the failure.

Use `!xxxx` instead of `!xxxx:server.domain.tld`

**Comment by jooola** [comment]
I added a way to strip the server address from the Room ID in case someone paste the Room ID including the server address. You can test the latest version of the script, should be working.

**Comment by jooola** [comment]
Hey, discard everything I just said, I am not totally awake today.

**Comment by jooola** [comment]
So I think I need more info about you issue in order to have an idea of what is going on.

**Comment by Killerhaschen** [comment]
I use Zabbix and Matrix on one Server as Doker Containers behind a reverse Proxy that uses Letsencrypt Certificates.
I tested:
- Use a different Matrix Server
- Downloaded the newes media_matrix.yml 
- look at Matrix oder Zabbix Container logs, but did not found anything
Uploading all logs and all configs seems not prectical. I have no idea where to look or what info you could need.

`0:00:00.000 [Debug] [Matrix Webhook] new request to: https://synapse.ewn.cloud/_matrix/client/r0/rooms/{ALERT.SENDTO}/send/m.room.message
00:00:00.055 [Debug] [Matrix Webhook] Request failed: Unknown room
00:00:00.057 [Debug] [Matrix Webhook] Error: Request failed: 403 Unknown room`

**Comment by Killerhaschen** [comment]
Is there anything else i can upload that could help ?

**Comment by jooola** [comment]
Something is wrong in your configuration, the room ID is not properly set. Check your configuration again and be sure to either put the room ID in your users media settings or globally in the matrix webhook settings.

**Comment by Killerhaschen** [comment]
I cloud only Provide the full Zabbix Container log and that is huge, because there i monitor a lot ob websides and every response is conpletly in the logs. Do you have any idea how i can stop this?
Setting it Globaly works for me. I dublicated the working profile and testet it again, if i try to get the roomID from the User it fails.

I tried to add the room to the error by changing th last lines of the script to:
``
} catch (error) {
    Zabbix.Log(4, '[Matrix Webhook] Error: ' + error)
    throw 'Sending failed: ' + error + 'room:'+ Matrix.room
}
``
That results to this error:
``
Sending failed: Request failed: 403 Unknown roomroom:{ALERT.SENDTO}
``
So it seems, that its not replaces by the Uservalue.

**Comment by jooola** [comment]
> I cloud only Provide the full Zabbix Container log and that is huge, because there i monitor a lot ob websides and every response is conpletly in the logs. Do you have any idea how i can stop this?

This is not in the scope of this ticket, please search the internet.


> I tried to add the room to the error by changing th last lines of the script to:

The first logs already provide this information, the `{ALERT.SENDTO}` entry defined in the users media settings, is supposed to be replaced by the roomID:
```
00:00:00.000 [Debug] [Matrix Webhook] new request to: https://server.domain.tld/_matrix/client/r0/rooms/{ALERT.SENDTO}/send/m.room.message
00:00:00.055 [Debug] [Matrix Webhook] Request failed: Unknown room
00:00:00.057 [Debug] [Matrix Webhook] Error: Request failed: 403 Unknown room
```
Please read the zabbix documentation about webhooks, and about testing webhooks: https://www.zabbix.com/documentation/current/manual/config/notifications/media/webhook

Here is how my user media settings are: 
The send to 
![image](https://user-images.githubusercontent.com/19195485/123541422-d1a60b00-d744-11eb-9da2-810ec215e223.png)

**Comment by jooola** [comment]
See https://github.com/jooola/zabbix-matrix-webhook#zabbix-webhook-configuration

**Comment by Killerhaschen** [comment]
The problem was my misconfiguration of zabbix.
I did not knew, that a trigger goes to an action that sends the message.
I configured my action "Report problems to Zabbix administrators" in the "Operations" to "Send only to" Telegram. That was why never a message over matrix was sent. For any reason set "Send only to" to all did not work for me. So i have now many Operations :D
