### ISSUE TITLE
How to Create Matrix Media Type - It's Not Working

### ISSUE THREAD

**Issue by facb69** [jooola/zabbix-matrix-webhook#9]
Hi there,
I'm trying to use this webhook but I think I'm missing something.
I followed the README instructions but there are no information about creating the Matrix media type. I tried different ways but it keeps failing.
Last error was: SyntaxError: parse error (line 1)
Can someone try to help me out, please?
Thank you.

**Comment by jooola** [comment]
The configuration of the web hook can be found here: https://github.com/jooola/zabbix-matrix-webhook#zabbix-webhook-configuration

If you still can't figure out what is going wrong, I'll first need more information about your setup otherwise I am blind.

**Comment by facb69** [comment]
Looks I don't know how to create the Matrix Media Type

![Captura de tela_2021-08-24_15-23-50](https://user-images.githubusercontent.com/8806966/130669750-eb1b587e-9214-44be-b63b-41220f965db0.png)

**Comment by facb69** [comment]
Here's the user configuration

![Captura de tela_2021-08-24_15-25-12](https://user-images.githubusercontent.com/8806966/130669924-15de5e31-f4db-4b46-977c-81b0cb0a8660.png)

**Comment by jooola** [comment]
The script section seem to be wrong, and your parameters as well. Do a clean import of the `media_matrix.yml` file, and try again.

**Comment by jooola** [comment]
I just update the setup documentation, maybe it helps ?

**Comment by facb69** [comment]
I'll trying it right now!

**Comment by facb69** [comment]
Sorry, it didn't work.
Error: SyntaxError: parse error (line 1)
Zabbix is 5.2

**Comment by jooola** [comment]
Please provide more information, otherwise I can't really help you.

**Comment by facb69** [comment]
Sorry to insist but here's what I did:

- followed all the documentation provided.
- configured my Zabbix Server 5.2 to alert when a host is down.
- created media type matrix as mentioned in  new documentation
- copied media-matrix.yml to  my zabbix alert scripts folder (which is stated in zabbix_server.conf)
- did not chage anything on media-matrix.yml
- configured my user to use Matrix media type as mentioned in new documentation
- restarted zabbix server and stopped zabbix agent on hosts
- the alert shows up but the message is not bridged with error SyntaxError: parse error (line 1)

Here are all the screens 

![Captura de tela_2021-08-24_17-32-56](https://user-images.githubusercontent.com/8806966/130686686-c666aca2-1e7d-4b62-abdb-2b643d0c8a59.png)

![Captura de tela_2021-08-24_17-35-24](https://user-images.githubusercontent.com/8806966/130686709-1acc4539-7d98-42fc-bacc-5e06ce153b9e.png)

![Captura de tela_2021-08-24_17-35-57](https://user-images.githubusercontent.com/8806966/130686721-f794ecad-060d-4f39-ae2d-8f548d18370f.png)

**Comment by facb69** [comment]
Hope you can help but I'll understand if I'm bothering too much.
Thanks anyway.

**Comment by jooola** [comment]
Please read the Zabbix documentation on:
- how to import media types: https://www.zabbix.com/documentation/current/manual/xml_export_import/media
- how to configure a webhook

`media_matrix.yml` is not an alert script.

**Comment by facb69** [comment]
Ok. I never used any other way but alert scripts.
I'll look into it.
I thank you and apologize.

**Comment by facb69** [comment]
@jooola 
I finally made it!
Thank you so much for the code and, mostly, the pacience. :smiley:
